# -*- coding: utf-8 -*-
"""Ganime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o0qOQvFkF-rgtVwVStjYgC7qAN1E5xm0

#Dependencies
"""

!pip install torch
!pip install Pillow
!pip install orchvision
!pip install gradio

from PIL import Image
import torch
import gradio as gr

"""#Building the System"""

model = torch.hub.load("bryandlee/animegan2-pytorch:main", "generator", pretrained="face_paint_512_v1")

face2paint = torch.hub.load(
    'bryandlee/animegan2-pytorch:main', 'face2paint', 
    size=512, device="cpu"
)

def inference(img):
    out = face2paint(model, img)
    return out

title = "GANime"

description = " Upload a Photo then click submit, wait for the filter to apply and generate a new picture. "

gr.Interface(inference, gr.inputs.Image(type="pil"), gr.outputs.Image(type="pil"),title=title,description=description,enable_queue=True).launch()

